### ISSUE TITLE
Citations?

### ISSUE THREAD

**Issue by rckirby** [FInAT/FInAT#71]
We have a bunch of FIAT elements that could benefit from being hooked up to the firedrake citations engine.

**Comment by dham** [comment]
well technically it's the PETSc citations engine. Probably what you should do is put the registration code into FInAT, protected by a try clause around the PETSc import so as not to create a hard dependency on PETSc.

**Comment by miklos1** [comment]
Ideally they should be added in FIAT.  Perhaps make this proposal there as well.  If it's advertised as PETSc citations engine rather than Firedrake citations engine, they could be more keen on letting it in.  Of course, with try clause around import, so no hard dependency.

However, if it cannot go to FIAT, I'm fine with these citations only being added through the FInAT wrapper.

**Comment by wence-** [comment]
See FEniCS/fiat#61, I think it's easier if one just doesn't bring PETSc in at all in FIAT and downstream consumers can hook it up if they like.

**Comment by miklos1** [comment]
> See [FEniCS/fiat#61](https://github.com/FEniCS/fiat/issues/61), I think it's easier if one just doesn't bring PETSc in at all in FIAT and downstream consumers can hook it up if they like.

So you just abstract it from any particular implementation.  Good idea!

**Comment by rckirby** [comment]
Oh, so @wence- beat me to this but in a different place.  One could have FIAT elements provide a method `citation()` returning a pair of strings `(key, bibtex)` and then clients could do with it as they please, including registering it with the PETSc citation index.  I think FIAT should not even think about trying to import PETSc.  FInAT's wrapper constructor could probably automate this for FIAT elements?

**Comment by connorjward** [comment]
Closing as replaced by https://github.com/firedrakeproject/fiat/issues/112
