### ISSUE TITLE
[meta] Unimplemented duals

### ISSUE THREAD

**Issue by ReubenHill** [FInAT/FInAT#95]
Upon the merge of #89 we still have elements which do not advertise a dual (i.e. they cannot be interpolated onto).
This meta issue aims to catalogue these and provide notes on how to support them.
The tickboxes can be ticked when they have been supported.

 - [ ] `HDivElement`/`HCurlElement` (e.g. RTCF/RTCE) (**DONE?**)
   - *Tests*: see `firedrake/tests/regression/test_interpolate.py::test_hdiv_2d` and `tests/regression/test_interpolate.py::test_hcurl_2d`
   - *How to support*: https://github.com/FInAT/FInAT/pull/98 (for full support need `EnrichedElement` as well)
 
 - [ ] `EnrichedElement`
   - *Tests*: No direct firedrake tests but `firedrake/tests/regression/test_interpolate.py::test_hdiv_2d` will trigger the `NotImplementedError`
   - *How to support*: See discussion in #89 starting with 
     - [@wence- 's attempt at implementation](https://github.com/FInAT/FInAT/pull/89#issuecomment-903631589), 
     - later [@ReubenHill 's suggested dual basis](https://github.com/FInAT/FInAT/pull/89#issuecomment-903781108),
     - further the [optimisation of `dual_evaluation` by composing it from the `dual_evaluation`s of the contained `.elements`](https://github.com/FInAT/FInAT/pull/89#issuecomment-903800830)
     - concluding with [remarks about the need for tsfc changes](https://github.com/FInAT/FInAT/pull/89#issuecomment-904466304) (@wence- discusses this in more depth earlier in the exchange)

 - [ ] Elements with derivative nodes
   - *Tests*: None known of but interpolation into something like Hermite should trigger the `NotImplementedError`
   - *How to support*:
     1. Translate the `deriv_dict` in FIAT for such elements into a dual evaluation tensor `Q` as we do for other elements - see `FIAT.pointwise_dual` and [this comment](https://github.com/FInAT/FInAT/issues/94#issuecomment-906438304) on #94 
     2. Take derivatives of incoming UFL expression as part of python callable that represents your function to dual evaluate. I don't really understand this option but it is what started to be implemented in #57 .

 - [ ] Zany elements
   - *Tests*: None know of. `firedrake/tests/regression/test_interpolate_zany.py` does not actually interpolate onto zany elements.
   - *How to support*: Not sure yet, I don't know much about Zany elements

Possibly interested parties @wence- @dham @pefarrell @rckirby

**Comment by wence-** [comment]
I had another go at the dual for enriched elements. I think if you remove the requirement that every element has to advertise a `dual_basis` property (and instead you can get away with just supporting `dual_evaluation`) then I have something that works. I think to make this fully composable, all the element modifiers (like `TensorProductElement` and so forth) need to implement `dual_evaluation` without advertising a `dual_basis` property (because they can't construct it).

I realise that a long time ago I was arguing heavily _for_ having a `dual_basis` property for composition, but I suppose I was probably wrong at the time. I think this would also probably mean that the `fn` that one passes into `dual_evaluation` is decomposable for the tensor product case (so that one can apply the factor duals appropriately). My approach in #98 then also doesn't work (because that promotes the `Q` into the vector space, whereas if one has a dual evaluation of the scalar wrappee one needs to probably demote the expression from the vector into the scalar space)

**Comment by ReubenHill** [comment]
> I had another go at the dual for enriched elements. I think if you remove the requirement that every element has to advertise a `dual_basis` property (and instead you can get away with just supporting `dual_evaluation`) then I have something that works. I think to make this fully composable, all the element modifiers (like `TensorProductElement` and so forth) need to implement `dual_evaluation` without advertising a `dual_basis` property (because they can't construct it).
> 
> I realise that a long time ago I was arguing heavily _for_ having a `dual_basis` property for composition, but I suppose I was probably wrong at the time. I think this would also probably mean that the `fn` that one passes into `dual_evaluation` is decomposable for the tensor product case (so that one can apply the factor duals appropriately). My approach in #98 then also doesn't work (because that promotes the `Q` into the vector space, whereas if one has a dual evaluation of the scalar wrappee one needs to probably demote the expression from the vector into the scalar space)

What's the fundamental problem that you've encountered given the discussion we had in #89 (see links in issue comment at the top)?

**Comment by wence-** [comment]
So if the element can provide a dual_basis property, then in the evaluation method we can just call `fn(dual_basis_points)` and do whatever. If we don't have the dual basis property then we don't know the points so all we can do is have a rule for composing the evaluation of the duals of the wrapped elements (e.g. the factors in a tensor product element). But now, the expression might not be the right shape (so we need to modify it when pushing it to the factors) which requires us to know more about it than just "here is a function we can apply to some points".

For example, for the hdiv/curl element modifiers, the vector-valued expression that we can evaluate their dual against needs to be picked into components for the scalar pieces inside to evaluate. This might work since the return value of the function is `gem`, so we can actually wrap it up.

Maybe this will work...

**Comment by ReubenHill** [comment]
Regarding #98 and "promot[ing] the `Q` into the vector space" I'll need to see some explanation of the maths as requested in that PR to be able to comment more fully.

Returning to what you've written above:

I believe my proposition [here](https://github.com/FInAT/FInAT/pull/89#issuecomment-903781108) had the dual basis method putting the `Q` tensors of the `EnrichedElement` subelements together such that it has the right shape for contraction with your expression without having to modify the shape. 

If I have understood you, you are proposing _not_ advertising a dual basis for `EnrichedElement` and instead only having a dual evaluation method which modifies the shape of the incoming expression (which I presume you mean to be either `fn` or the UFL expression that `fn` converts to gem when it eats a point set) and then manually doing the sub-element contractions. Is that correct?

**Comment by ReubenHill** [comment]
> For example, for the hdiv/curl element modifiers, the vector-valued expression that we can evaluate their dual against needs to be picked into components for the scalar pieces inside to evaluate. This might work since the return value of the function is `gem`, so we can actually wrap it up.

On this, and I really might not be understanding you, but isn't this what symbolic kronecker deltas in gem are meant to deal with?

**Comment by wence-** [comment]
> > For example, for the hdiv/curl element modifiers, the vector-valued expression that we can evaluate their dual against needs to be picked into components for the scalar pieces inside to evaluate. This might work since the return value of the function is `gem`, so we can actually wrap it up.
> 
> On this, and I really might not be understanding you, but isn't this what symbolic kronecker deltas in gem are meant to deal with?

Yes, that's exactly right. But I need to think about how to do this.

**Comment by connorjward** [comment]
Closing as replaced by https://github.com/firedrakeproject/fiat/issues/109
